# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "grupo_23"
      MYSQL_PASSWORD: "grupo_23"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
